"""Writes the accent colour rules (static/css/themes.css) and the matching picker markup (templates/index.html).

Run again after changing ACCENTS: python tools/make_accents.py   (plain Python, no packages needed).
Each accent gets a bright variant for the dark themes and a deeper one for the light themes, with a text colour chosen
for contrast, so every accent stays readable on every theme."""
import colorsys
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
THEMES = ROOT / "static" / "css" / "themes.css"
INDEX = ROOT / "templates" / "index.html"

# key, label, hue, saturation %, lightness % (for the dark themes). "lime" is the themes' own colour and needs no rule.
GROUPS = [
    ("Greens", [("lime", "Lime", 84, 76, 55), ("green", "Green", 142, 70, 58), ("emerald", "Emerald", 158, 72, 52), ("mint", "Mint", 160, 70, 70),
                ("spearmint", "Spearmint", 150, 55, 72), ("sage", "Sage", 100, 25, 62), ("teal", "Teal", 174, 75, 50)]),
    ("Blues", [("cyan", "Cyan", 188, 90, 58), ("ice", "Ice", 195, 70, 84), ("sky", "Sky", 199, 92, 66), ("blue", "Blue", 208, 100, 78), ("azure", "Azure", 213, 90, 62),
               ("cobalt", "Cobalt", 222, 85, 62), ("royal", "Royal", 230, 82, 66), ("indigo", "Indigo", 243, 80, 70)]),
    ("Purples and pinks", [("lavender", "Lavender", 255, 70, 82), ("violet", "Violet", 258, 85, 72), ("purple", "Purple", 272, 78, 68), ("orchid", "Orchid", 292, 70, 68),
                           ("magenta", "Magenta", 310, 80, 64), ("fuchsia", "Fuchsia", 322, 85, 62), ("bubblegum", "Bubblegum", 330, 85, 80), ("pink", "Pink", 336, 85, 70),
                           ("rose", "Rose", 350, 85, 66)]),
    ("Warm", [("red", "Red", 4, 85, 62), ("coral", "Coral", 12, 90, 66), ("peach", "Peach", 20, 90, 78), ("tangerine", "Tangerine", 24, 95, 58), ("amber", "Amber", 38, 89, 63),
              ("gold", "Gold", 46, 92, 56), ("yellow", "Yellow", 56, 95, 60), ("lemon", "Lemon", 60, 90, 72)]),
    ("Neutral", [("silver", "Silver", 220, 8, 78), ("slate", "Slate", 215, 25, 66), ("stone", "Stone", 30, 12, 68), ("snow", "Snow", 0, 0, 94)]),
]


def hsl(h, s, l):
    r, g, b = colorsys.hls_to_rgb(h / 360, l / 100, s / 100)
    return "#%02x%02x%02x" % (round(r * 255), round(g * 255), round(b * 255))


def luminance(color):
    channels = [int(color[i:i + 2], 16) / 255 for i in (1, 3, 5)]
    linear = [c / 12.92 if c <= 0.03928 else ((c + 0.055) / 1.055) ** 2.4 for c in channels]
    return 0.2126 * linear[0] + 0.7152 * linear[1] + 0.0722 * linear[2]


def contrast(a, b):
    return (max(luminance(a), luminance(b)) + 0.05) / (min(luminance(a), luminance(b)) + 0.05)


def text_on(color):
    """Dark or white, whichever reads better on `color`."""
    dark, light = "#0e1011", "#ffffff"
    return dark if contrast(color, dark) >= contrast(color, light) else light


def bright_variant(h, s, l):
    """The accent for the dark themes, lightened a little if neither dark nor white text is readable on it."""
    while max(contrast(hsl(h, s, l), "#0e1011"), contrast(hsl(h, s, l), "#ffffff")) < 4.5 and l < 90:
        l += 1
    return hsl(h, s, l)


def light_variant(h, s):
    """The accent for the light themes: darkened until white text (and the accent as text on white) reads well."""
    l = 36
    while contrast(hsl(h, min(s, 85), l), "#ffffff") < 4.6 and l > 10:
        l -= 1
    return hsl(h, min(s, 85), l), hsl(h, min(s, 85), max(l - 9, 6))


def light_themes(css: str):
    names = []
    for name, body in re.findall(r'body\[data-theme="([a-z0-9]+)"\]\s*\{([^}]*)\}', css):
        bg = re.search(r"--bg:\s*(#[0-9a-fA-F]{6})", body)
        if bg and luminance(bg.group(1)) > 0.5:
            names.append(name)
    return names


def build_css(light):
    selector = ", ".join(f'[data-theme="{name}"]' for name in light)
    lines = ["/* accents:start (generated by tools/make_accents.py) */"]
    for _, accents in GROUPS:
        for key, _, h, s, l in accents:
            if key == "lime":
                continue
            bright = bright_variant(h, s, l)
            deep = hsl(h, s, max(l - 12, 8))
            lines.append(f'body[data-accent="{key}"] {{ --green: {bright}; --green-dark: {deep}; --on-accent: {text_on(bright)}; }}')
    lines.append("/* the same accents, deepened so they stay readable on the light themes */")
    for _, accents in GROUPS:
        for key, _, h, s, l in accents:
            if key == "lime":
                continue
            tone, tone_deep = light_variant(h, s)
            lines.append(f'body[data-accent="{key}"]:is({selector}) {{ --green: {tone}; --green-dark: {tone_deep}; --on-accent: #ffffff; }}')
    lines.append("/* accents:end */")
    return "\n".join(lines)


def build_picker():
    options = []
    for group, accents in GROUPS:
        items = "".join(f'<option value="{key}" data-color="{"#a3e635" if key == "lime" else bright_variant(h, s, l)}">{label}</option>' for key, label, h, s, l in accents)
        options.append(f'<optgroup label="{group}">{items}</optgroup>')
    return "".join(options)


def main():
    css = THEMES.read_text(encoding="utf-8")
    block = build_css(light_themes(css))
    if "/* accents:start" in css:
        css = re.sub(r"/\* accents:start.*?/\* accents:end \*/", lambda _: block, css, flags=re.S)
    else:
        css, count = re.subn(r'body\[data-accent="blue"\][^\n]*\n?', lambda _: block + "\n", css)
        assert count == 1, "the old accent rules were not found"
    THEMES.write_text(css, encoding="utf-8", newline="\n")

    page = INDEX.read_text(encoding="utf-8")
    page, count = re.subn(r'(<select class="setting-input" data-setting="accent" hidden>).*?(</select>)', lambda m: m.group(1) + build_picker() + m.group(2), page, flags=re.S)
    if count == 0:
        page, count = re.subn(r'<select class="setting-input" data-setting="accent">.*?</select>', lambda _: '<select class="setting-input" data-setting="accent" hidden>' + build_picker() + "</select>", page, flags=re.S)
    assert count == 1, "the accent select was not found"
    INDEX.write_text(page, encoding="utf-8", newline="\n")
    total = sum(len(accents) for _, accents in GROUPS)
    print(f"{total} accents; light themes: {', '.join(light_themes(css))}")


if __name__ == "__main__":
    main()
